// Catalog version - bump to force Firestore wipe and reseed
export const CATALOG_VERSION = 9;

const starterProducts = [
    {
        name: "Apple AirPods Pro (3rd Gen)",
        price: 74.7,
        description: "The latest Apple AirPods Pro with active noise cancellation, Adaptive Audio, and up to 30 hours total listening time.",
        category: "Audio",
        image: "/products/01_Apple_AirPods_Pro_3rd_Gen.png",
        isFeatured: true, isPromoted: true, sortOrder: 1, catalogVersion: 6,
    },
    {
        name: "Meta Quest 3 Advanced VR Headset",
        price: 75,
        description: "Meta's most powerful mixed reality headset. Full-color passthrough, next-gen chipset, and an expansive library of VR and MR experiences.",
        category: "Tech & Gadgets",
        image: "/products/02_Meta_Quest_3_Advanced_VR_Headset.png",
        isFeatured: true, isPromoted: true, sortOrder: 2, catalogVersion: 6,
    },
    {
        name: "Withings Body Scan Smart Scale",
        price: 89.7,
        description: "Advanced health tracking scale measuring weight, body composition, nerve activity, and vascular age. Sync with your smartphone for deep health insights.",
        category: "Health & Fitness",
        image: "/products/03_Withings_Body_Scan_Smart_Scale.png",
        isFeatured: true, isPromoted: true, sortOrder: 3, catalogVersion: 6,
    },
    {
        name: "Breville Barista Express Espresso Machine",
        price: 239.7,
        description: "All-in-one espresso machine with integrated conical burr grinder. Grind, dose, tamp, and extract cafe-quality espresso at home.",
        category: "Home & Kitchen",
        image: "/products/05_Breville_Barista_Express_Espresso_Machine.png",
        isFeatured: true, isPromoted: true, sortOrder: 5, catalogVersion: 6,
    },
    {
        name: "Shokz OpenRun Pro Bone Conduction Headphones",
        price: 27,
        description: "Premium open-ear headphones using bone conduction technology. Stay aware of your surroundings while enjoying high-quality audio outdoors.",
        category: "Audio",
        image: "/products/06_Shokz_OpenRun_Pro_Bone_Conduction_Headphones.png",
        isFeatured: true, isPromoted: true, sortOrder: 6, catalogVersion: 6,
    },
    {
        name: "Dyson Airwrap Multi-Styler Complete Long",
        price: 179.7,
        description: "The iconic multi-styler that curls, waves, smooths, and dries using Coanda airflow with no extreme heat. Includes attachments for all hair types.",
        category: "Beauty & Personal Care",
        image: "/products/07_Dyson_Airwrap_Multi_Styler_Complete_Long.png",
        isFeatured: true, isPromoted: true, sortOrder: 7, catalogVersion: 6,
    },
    {
        name: "Fujifilm Instax Mini EVO Instant Camera",
        price: 59.7,
        description: "Hybrid instant camera combining digital shooting with analog printing. 10 lens and film effects, app connectivity, and a premium retro design.",
        category: "Photography",
        image: "/products/08_Fujifilm_Instax_Mini_EVO_Instant_Camera.png",
        isFeatured: true, isPromoted: true, sortOrder: 8, catalogVersion: 6,
    },
    {
        name: "Philips Hue Smart Light Starter Kit",
        price: 59.7,
        description: "Transform your home lighting with smart LED bulbs and the Hue Bridge. Control millions of colors via app, voice, or schedule for any mood.",
        category: "Smart Home",
        image: "/products/09_Philips_Hue_Smart_Light_Starter_Kit.png",
        isFeatured: true, isPromoted: true, sortOrder: 9, catalogVersion: 6,
    },
    {
        name: "GoPro HERO12 Black Action Camera",
        price: 119.7,
        description: "5.3K video, HyperSmooth 6.0 stabilization, and unlimited cloud backup. Waterproof to 33ft out of the box. The ultimate action camera for creators.",
        category: "Photography",
        image: "/products/10_GoPro_HERO12_Black_Action_Camera.png",
        isFeatured: true, isPromoted: true, sortOrder: 10, catalogVersion: 6,
    },
    {
        name: "Sonos Era 100 Smart Speaker",
        price: 74.7,
        description: "Premium stereo smart speaker with Trueplay tuning, Bluetooth, and Wi-Fi. Works with Alexa, Google Assistant, and Apple AirPlay 2.",
        category: "Audio",
        image: "/products/11_Sonos_Era_100_Smart_Speaker.png",
        isFeatured: true, isPromoted: true, sortOrder: 11, catalogVersion: 6,
    },
    {
        name: "Samsung T9 Portable SSD (2TB)",
        price: 53.7,
        description: "Blazing-fast 2TB portable SSD with USB 3.2 Gen 2x2 speeds up to 2,000 MB/s. Rugged, IP65-rated, and compact for on-the-go creators.",
        category: "Tech & Gadgets",
        image: "/products/12_Samsung_T9_Portable_SSD_2TB.png",
        isFeatured: true, isPromoted: true, sortOrder: 12, catalogVersion: 6,
    },
    {
        name: "Amazon Kindle Paperwhite Bundle",
        price: 28.5,
        description: "Kindle Paperwhite with premium fabric cover and 3-month Kindle Unlimited. 300 ppi glare-free display, waterproof, up to 10 weeks battery life.",
        category: "Tech & Gadgets",
        image: "/products/Extra_Amazon_Kindle_Paperwhite_Bundle.png",
        isFeatured: true, isPromoted: true, sortOrder: 13, catalogVersion: 6,
    },
    {
        name: "Apple AirPods Pro 2nd Gen MagSafe USB-C",
        price: 68.7,
        description: "Active Noise Cancellation, Adaptive Transparency, and Personalized Spatial Audio. MagSafe charging case with USB-C and up to 30 hours total listening time.",
        category: "Audio",
        image: "/products/Extra_Apple_AirPods_Pro_2nd_Generation_MagSafe_USB_C.png",
        isFeatured: true, isPromoted: true, sortOrder: 14, catalogVersion: 6,
    },
    {
        name: "Beats Studio Pro Wireless Headphones",
        price: 104.7,
        description: "Professional over-ear headphones with active noise cancelling, lossless audio via USB-C, and up to 40 hours battery life. Works with Apple and Android.",
        category: "Audio",
        image: "/products/Extra_Beats_Studio_Pro_Wireless_Headphones.png",
        isFeatured: true, isPromoted: true, sortOrder: 15, catalogVersion: 6,
    },
    {
        name: "Breville Barista Express With Box",
        price: 254.7,
        description: "The complete Breville Barista Express bundle with everything needed to pull cafe-quality espresso shots at home, fresh from the integrated grinder.",
        category: "Home & Kitchen",
        image: "/products/Extra_Breville_Barista_Express_Espresso_Machine_With_Box.png",
        isFeatured: true, isPromoted: true, sortOrder: 16, catalogVersion: 6,
    },
    {
        name: "DJI Mavic 3 Fly More Combo",
        price: 659.7,
        description: "Professional drone with Hasselblad camera, 46-min flight time, and 15km transmission. Includes extra batteries, charging hub, and carry bag.",
        category: "Photography",
        image: "/products/Extra_DJI_Mavic_3_Fly_More_Combo.png",
        isFeatured: true, isPromoted: true, sortOrder: 17, catalogVersion: 6,
    },
    {
        name: "Dyson V15 Detect Cordless Vacuum",
        price: 224.7,
        description: "Most powerful Dyson cordless vacuum with laser dust detection, dynamic load sensor, and 60-min run time. Reveals microscopic dust invisible to the naked eye.",
        category: "Home & Kitchen",
        image: "/products/Extra_Dyson_V15_Detect_Cordless_Vacuum.png",
        isFeatured: true, isPromoted: true, sortOrder: 18, catalogVersion: 6,
    },
    {
        name: "Garmin Forerunner 965 Smartwatch",
        price: 179.7,
        description: "Premium GPS running smartwatch with AMOLED display, full-color maps, training readiness score, and up to 23 days battery life.",
        category: "Health & Fitness",
        image: "/products/Extra_Garmin_Forerunner_965_Smartwatch.png",
        isFeatured: true, isPromoted: true, sortOrder: 19, catalogVersion: 6,
    },
    {
        name: "Instant Pot Duo 7-in-1 Electric Pressure Cooker",
        price: 29.7,
        description: "The world's best-selling multi-cooker. Pressure cook, slow cook, rice cook, steam, saute, make yogurt, and keep warm all in one appliance.",
        category: "Home & Kitchen",
        image: "/products/Extra_Instant_Pot_Duo_7_in_1_Electric_Pressure_Cooker.png",
        isFeatured: true, isPromoted: true, sortOrder: 20, catalogVersion: 6,
    },
    {
        name: "JBL Live Pro 2 Earbuds",
        price: 44.7,
        description: "True adaptive noise cancelling earbuds with Smart Ambient mode, 40-hour total battery, and 6-mic TrueVoice call technology. JBL Signature Sound with EQ.",
        category: "Audio",
        image: "/products/Extra_JBL_Live_Pro_2_Earbuds.png",
        isFeatured: true, isPromoted: true, sortOrder: 21, catalogVersion: 6,
    },
    {
        name: "75W Box Mod Vape Kit with Sub-Ohm Tank",
        price: 9,
        description: "Rechargeable 75W regulated box mod kit with adjustable wattage, OLED display, and sub-ohm tank. Single 18650 external battery (not included). Supports Variable Wattage, Bypass, Temperature Control (Ni/Ti/SS), and TCR modes. Wattage range 1–75W, resistance range 0.05–3.5O, temp range 100–315°C. 510-thread connection, USB-C charging. Kit includes: 75W mod, sub-ohm tank (2–4ml), 0.3O & 0.5O coils, USB cable, and user manual. Zinc alloy & stainless steel build. Dimensions: ~45 × 23 × 70.5mm.",
        category: "Vapes & E-Cigarettes",
        image: "/products/vapekit.jpg",
        isFeatured: true, isPromoted: true, sortOrder: 22, catalogVersion: 6,
    },
];

const massageCatalogImages: Record<string, string> = {
    "Massage Guns": "/products/massage-gun-catalog.png",
    "Neck Massagers": "/products/neck-massager-catalog.png",
    "Foot Massagers": "/products/foot-massager-catalog.png",
    "Massage Chairs": "/products/massage-chair-catalog.png",
    "Back Massagers": "/products/back-massager-catalog.png",
    "Scalp Massagers": "/products/scalp-massager-catalog.png",
    "Heating Pads": "/products/heating-pad-catalog.png",
    "Spa & Wellness Tools": "/products/spa-wellness-catalog.png",
    "Electric Massagers": "/products/electric-massager-catalog.png",
    "Portable Massagers": "/products/portable-massager-catalog.png",
};

const massageProductGroups = [
    {
        category: "Massage Guns",
        names: ["Deep Tissue Pro Massage Gun", "Mini Percussion Muscle Gun", "QuietForce Recovery Massage Gun", "Athlete Pro 6-Head Massage Gun", "Compact USB-C Massage Gun", "Carbon Grip Therapy Gun", "Heated Percussion Massage Gun", "Travel Case Muscle Recovery Gun", "LCD Touch Massage Gun", "Long Battery Massage Gun", "Soft Head Relaxation Gun", "Sports Recovery Massage Gun"],
        prices: [24.5, 18.75, 29.99, 34.5, 16.9, 27.4, 31.25, 22.8, 28.6, 25.95, 19.4, 33.75],
    },
    {
        category: "Neck Massagers",
        names: ["Smart Electric Neck Massager", "Heated Cervical Neck Relaxer", "EMS Pulse Neck Massager", "Wireless Shoulder Neck Massager", "U-Shape Portable Neck Therapy Device", "Neck Heat Compression Massager", "Foldable Travel Neck Massager", "Rechargeable Neck Pain Relief Massager", "Magnetic Neck Pulse Massager", "Deep Kneading Neck Massager", "Office Neck Relief Massager", "Silicone Pad Neck Therapy Massager"],
        prices: [12.8, 16.5, 14.25, 21.75, 18.4, 19.95, 15.6, 17.9, 13.75, 24.5, 14.9, 16.25],
    },
    {
        category: "Foot Massagers",
        names: ["Shiatsu Heated Foot Massager", "Air Compression Foot Relaxer", "Remote Control Foot Therapy Machine", "Deep Kneading Foot Massager", "Foldable Foot Spa Massager", "Reflexology Roller Foot Massager", "Electric Foot Warmer Massager", "Calf and Foot Compression Massager", "Compact Home Foot Massager", "Vibration Foot Relief Pad", "Leg Circulation Foot Massager", "Premium Foot Spa Bath Massager"],
        prices: [39.5, 44.75, 35.2, 42.9, 29.99, 9.8, 24.5, 49.5, 31.75, 18.6, 46.9, 37.25],
    },
    {
        category: "Massage Chairs",
        names: ["Zero Gravity Full Body Massage Chair", "Compact Recliner Massage Chair", "SL Track Heated Massage Chair", "Luxury Home Massage Chair", "Airbag Compression Massage Chair", "Smart Body Scan Massage Chair", "Bluetooth Relaxation Massage Chair", "Space Saving Massage Recliner", "Foot Roller Massage Chair", "Premium Office Massage Chair", "Deep Kneading Massage Recliner", "Full Body Shiatsu Massage Chair"],
        prices: [249.5, 199.99, 289.75, 349.5, 279.4, 319.8, 259.9, 229.5, 299.99, 219.75, 269.25, 339.9],
    },
    {
        category: "Back Massagers",
        names: ["Heated Back Relief Cushion", "Lumbar Support Back Massager", "Shiatsu Back and Shoulder Pad", "Memory Foam Back Massage Pillow", "Corded Heat Vibration Back Pad", "Upper Back Kneading Massager", "Lower Back Therapy Massager", "Chair Strap Back Massager", "Full Spine Heat Massage Pad", "Portable Back Pain Relief Pillow", "Deep Tissue Back Massage Cushion", "Ergonomic Back Relaxation Pad"],
        prices: [22.4, 18.9, 26.5, 19.75, 24.8, 29.4, 21.25, 17.6, 31.9, 20.5, 28.75, 23.95],
    },
    {
        category: "Scalp Massagers",
        names: ["Silicone Scalp Shampoo Brush", "Electric Scalp Massage Brush", "Waterproof Head Massager", "Soft Bristle Scalp Scrubber", "Rechargeable Scalp Therapy Brush", "Ergonomic Hair Wash Massager", "Deep Clean Scalp Massage Comb", "Vibration Scalp Relaxation Brush", "Travel Scalp Care Massager", "Spa Head Massage Brush", "Gentle Hair Growth Scalp Brush", "Premium Silicone Scalp Tool"],
        prices: [5.9, 11.5, 13.25, 4.8, 15.75, 6.25, 7.4, 12.95, 5.5, 8.2, 9.6, 6.9],
    },
    {
        category: "Heating Pads",
        names: ["Electric Heating Therapy Pad", "Washable Heat Compress Pad", "Neck and Shoulder Heating Wrap", "Fast Heat Pain Relief Pad", "Portable USB Heating Pad", "Large Back Heating Blanket", "Soft Plush Heating Pad", "Auto Shutoff Heat Therapy Pad", "Abdominal Warm Compress Pad", "Joint Relief Heating Wrap", "Travel Size Heating Pad", "Moist Heat Therapy Pad"],
        prices: [13.5, 15.75, 18.6, 14.25, 10.9, 22.5, 16.4, 17.95, 12.8, 15.2, 9.75, 19.4],
    },
    {
        category: "Spa & Wellness Tools",
        names: ["Hot Stone Spa Massage Set", "Facial Roller Wellness Kit", "Body Relaxation Cupping Set", "Aromatherapy Diffuser Spa Kit", "Gua Sha Facial Massage Tool", "Bath Spa Pillow Cushion", "Reflexology Massage Ball Set", "Ice Roller Recovery Tool", "Relaxation Eye Mask Set", "Home Spa Care Bundle", "Wellness Massage Oil Warmer", "Spa Therapy Accessory Kit"],
        prices: [18.5, 7.9, 12.4, 16.75, 6.5, 11.25, 8.6, 9.95, 7.25, 21.4, 19.75, 14.9],
    },
    {
        category: "Electric Massagers",
        names: ["Dual Head Electric Mini Massager", "Rechargeable Body Massager", "USB-C Quiet Electric Massager", "Multi Mode Vibration Massager", "Cordless Handheld Electric Massager", "Heated Electric Therapy Massager", "Palm Size Muscle Massager", "Deep Pulse Electric Massager", "Soft Touch Electric Body Massager", "Wireless Relaxation Massager", "5 Mode Electric Massage Device", "Home Use Electric Massager"],
        prices: [13.75, 18.2, 15.5, 16.9, 19.95, 23.6, 11.8, 17.4, 14.25, 18.75, 15.9, 20.5],
    },
    {
        category: "Portable Massagers",
        names: ["Pocket Mini Travel Massager", "Portable Muscle Relief Wand", "Cordless Travel Body Massager", "Compact Handheld Relaxation Tool", "USB Rechargeable Pocket Massager", "Mini Neck and Shoulder Massager", "Portable Deep Tissue Massager", "Travel Case Vibration Massager", "Lightweight Office Massager", "On The Go Therapy Massager", "Mini Heated Portable Massager", "Silent Portable Massage Device"],
        prices: [8.5, 12.75, 14.9, 10.6, 9.95, 13.4, 16.25, 11.5, 10.25, 12.2, 15.75, 9.4],
    },
];

const massageProducts = massageProductGroups.flatMap((group, groupIndex) => {
    return group.names.map((name, itemIndex) => {
        const price = group.prices[itemIndex];
        const originalPrice = Math.round(price * 2.6 * 100) / 100;

        return {
            name,
            price,
            originalPrice,
            description: `${name} sourced for resale with a reduced base cost, clean product visuals, and simple positioning for wellness, recovery, and home relaxation stores.`,
            category: group.category,
            image: massageCatalogImages[group.category] || "/products/massage-wellness-catalog.png",
            stock: 18 + ((groupIndex * 12 + itemIndex) % 33),
            source: "Verified Supplier",
            sourceProductId: `massage-${group.category.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${itemIndex + 1}`,
            sourceUrl: "",
            isFeatured: groupIndex < 3 && itemIndex < 2,
            isPromoted: groupIndex < 3 && itemIndex < 2,
            sortOrder: 100 + (groupIndex * 12) + itemIndex,
            catalogVersion: CATALOG_VERSION,
        };
    });
});

const jewelryProducts = [
    {
        "name": "1.5CT IGI Certified Marquise Cut Lab Grown Diamond Engagement Ring, 14K Yellow Gold, Nature Inspired Leaf Design",
        "price": 566.4,
        "originalPrice": 944,
        "description": "14K yellow gold engagement ring featuring a 1.5 carat IGI-certified marquise-cut lab-grown diamond, set in a nature-inspired leaf design band. Bridal/promise style with free shipping.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_01_diamond_engagement.jpg",
        "stock": 13,
        "source": "Verified Jewelry Supplier",
        "supplierName": "MollyjewelryUS",
        "sourceProductId": "jewelry-001-ring-01-diamond-engagement",
        "isFeatured": true,
        "isPromoted": true,
        "sortOrder": 301,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Personalized Birthstone Ring, Family Birthstone Ring, 18K Gold Daily Ring",
        "price": 17.68,
        "originalPrice": 35.36,
        "description": "18K gold-plated personalized birthstone ring, customizable with family members' birthstones. Popular as a mother's/graduation gift, lightweight daily-wear style.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_02_birthstone.jpg",
        "stock": 14,
        "source": "Verified Jewelry Supplier",
        "supplierName": "CraftedHarmonyCreate",
        "sourceProductId": "jewelry-002-ring-02-birthstone",
        "isFeatured": true,
        "isPromoted": true,
        "sortOrder": 302,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Solid Gold 0.25ct E VVS2 Dainty Round Lab Grown Diamond Promise Ring",
        "price": 298.95,
        "originalPrice": 427.07,
        "description": "14K solid gold promise/engagement ring set with a 0.25ct round lab-grown diamond (E color, VVS2 clarity) in a dainty, unique design. Limited stock, free shipping.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_03_promise_diamond.jpg",
        "stock": 15,
        "source": "Verified Jewelry Supplier",
        "supplierName": "ForeverForLove",
        "sourceProductId": "jewelry-003-ring-03-promise-diamond",
        "isFeatured": true,
        "isPromoted": true,
        "sortOrder": 303,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Vintage Floral Engraved 18K Gold Band Ring – Filigree Wedding Band",
        "price": 42.9,
        "originalPrice": 143,
        "description": "18K gold-plated wedding band with vintage floral filigree engraving, 7mm width. Free shipping.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_04_vintage_band.jpg",
        "stock": 16,
        "source": "Verified Jewelry Supplier",
        "supplierName": "KikaiJewels",
        "sourceProductId": "jewelry-004-ring-04-vintage-band",
        "isFeatured": true,
        "isPromoted": true,
        "sortOrder": 304,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Diamond Starburst Ring, 14K Solid Gold Star Setting Diamond Ring, Dome Women's Wedding Ring",
        "price": 908,
        "description": "14K solid gold dome wedding ring with a starburst-style diamond setting, by Ferkos Fine Jewelry. Limited stock.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_05_diamond_starburst.jpg",
        "stock": 17,
        "source": "Verified Jewelry Supplier",
        "supplierName": "FerkosFineJewelry (Etsy's Pick)",
        "sourceProductId": "jewelry-005-ring-05-diamond-starburst",
        "isFeatured": true,
        "isPromoted": true,
        "sortOrder": 305,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Thin Starburst Diamond Ring, Star Setting Celestial Ring, Minimalist",
        "price": 41.6,
        "originalPrice": 52,
        "description": "Minimalist thin celestial-style ring with a small starburst diamond setting, available in gold or silver tones.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_06_thin_starburst.jpg",
        "stock": 18,
        "source": "Verified Jewelry Supplier",
        "supplierName": "SamiJEWELS",
        "sourceProductId": "jewelry-006-ring-06-thin-starburst",
        "isFeatured": true,
        "isPromoted": true,
        "sortOrder": 306,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Personalized Initial Ring, Custom Letter Ring, Name Ring, 14K Gold Skinny Ring, 925 Stamped",
        "price": 30.34,
        "originalPrice": 82,
        "description": "14K gold-plated 925 sterling silver skinny ring, customizable with an initial or letter. Free shipping.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_07_personalized_initial.jpg",
        "stock": 19,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Aspirecreation",
        "sourceProductId": "jewelry-007-ring-07-personalized-initial",
        "isFeatured": true,
        "isPromoted": true,
        "sortOrder": 307,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Solid Gold Pave Diamond Wedding Band, 2.5mm Wavy Comfort Fit Ring",
        "price": 286.3,
        "description": "14K solid gold 2.5mm wavy wedding band, pave-set with diamonds, comfort-fit design for couples' anniversary jewelry.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_08_pave_diamond_band.jpg",
        "stock": 20,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-008-ring-08-pave-diamond-band",
        "isFeatured": true,
        "isPromoted": true,
        "sortOrder": 308,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "3.50 CT Oval Cut Moissanite Engagement Ring, 14K Solid Gold Anniversary Gift Ring, Oval Hidden Halo Promise Ring",
        "price": 223.85,
        "originalPrice": 319.79,
        "description": "14K solid gold engagement ring with a 3.50ct oval-cut moissanite in a hidden halo setting.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_09_oval_moissanite.jpg",
        "stock": 21,
        "source": "Verified Jewelry Supplier",
        "supplierName": "JewelQuestCo",
        "sourceProductId": "jewelry-009-ring-09-oval-moissanite",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 309,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Vintage 1990s 18 Ct Rolled Gold Large Sapphire Ring, Hallmarked 750 RG",
        "price": 107.36,
        "description": "Vintage 1990s rolled gold ring set with a large sapphire stone, hallmarked 750 RG.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_10_vintage_sapphire.jpg",
        "stock": 22,
        "source": "Verified Jewelry Supplier",
        "supplierName": "AllCelticIrish",
        "sourceProductId": "jewelry-010-ring-10-vintage-sapphire",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 310,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Custom 14K Gold Name Ring, Personalized Name Ring, Minimalist Jewelry Gift",
        "price": 12.26,
        "originalPrice": 40.87,
        "description": "14K gold-plated custom name ring, minimalist personalized jewelry gift.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_11_custom_name.jpg",
        "stock": 23,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Louiseshop12",
        "sourceProductId": "jewelry-011-ring-11-custom-name",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 311,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Birth Flower Ring, 925 Sterling Silver, Mother of Pearl Sakura Ring, Adjustable",
        "price": 29.4,
        "description": "925 sterling silver adjustable birth-flower ring with mother-of-pearl sakura detail, personalized birthstone gift.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_12_birth_flower_silver.jpg",
        "stock": 24,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-012-ring-12-birth-flower-silver",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 312,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Waterproof Gold Ring, Minimalist Gold Wave Ring, Abstract Gold Band, Adjustable Statement Ring",
        "price": 19.72,
        "description": "Waterproof gold-plated wave-design statement ring, adjustable minimalist band.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_13_waterproof_wave.jpg",
        "stock": 25,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-013-ring-13-waterproof-wave",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 313,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Multi Stone Ring, Diamond Wedding Band, Marquise Ring, Stacking Ring, Sterling Silver, Promise Ring",
        "price": 43.2,
        "description": "Sterling silver multi-stone stacking ring with marquise diamond-style accents.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_14_multi_stone.jpg",
        "stock": 26,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-014-ring-14-multi-stone",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 314,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Sterling Silver Vintage 18K Opal Ring Gold, Dainty Opal Engagement Ring, October's Birthstone",
        "price": 16.88,
        "description": "Sterling silver ring with 18K gold vermeil and dainty opal stone, October birthstone style.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_15_opal_vintage.jpg",
        "stock": 27,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-015-ring-15-opal-vintage",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 315,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Solid 14K Gold Stacking Rings, Set of 4 Textured Minimalist Bands",
        "price": 18,
        "description": "Set of four solid 14K gold textured minimalist stacking bands.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_16_stacking_set4.jpg",
        "stock": 28,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-016-ring-16-stacking-set4",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 316,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Gold Baguette Birthstone Ring, Dainty Stacking Birthstone Ring, Minimalist",
        "price": 20.31,
        "description": "14K gold-plated dainty baguette-cut birthstone stacking ring.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_17_baguette_birthstone.jpg",
        "stock": 29,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-017-ring-17-baguette-birthstone",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 317,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Personalized Heart Birthstone Ring, 2 Birthstone Ring, Mother's Ring, Dainty Stacking Jewelry",
        "price": 18.18,
        "description": "Dainty heart-shaped mother's ring with two personalized birthstones.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_18_heart_birthstone.jpg",
        "stock": 30,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-018-ring-18-heart-birthstone",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 318,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "10K Yellow Gold Initial Heart Ring, Diamond Cut Flower Letter Band",
        "price": 146.25,
        "description": "10K yellow gold heart-and-initial ring with diamond-cut flower letter band detailing.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_19_initial_heart_10k.jpg",
        "stock": 31,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-019-ring-19-initial-heart-10k",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 319,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Floral Moissanite Wedding Band, V Shape Curved Ring, Dainty Gold Stacking Ring, Minimal Bridal Jewelry",
        "price": 28.6,
        "description": "Gold V-shaped curved wedding band with floral moissanite detailing, minimalist bridal style.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_20_floral_moissanite_band.jpg",
        "stock": 32,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-020-ring-20-floral-moissanite-band",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 320,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K Solid Gold Stackable Ring Set, Minimalist Textured Bands, Handmade Boho Jewelry",
        "price": 12.75,
        "description": "18K solid gold handmade boho stackable ring set with textured minimalist bands.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_21_stackable_set.jpg",
        "stock": 33,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-021-ring-21-stackable-set",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 321,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K Gold Flower Ring, Camellia Ring, Adjustable Open Ring, Pearl Floral Jewelry",
        "price": 18.29,
        "description": "18K gold adjustable open ring shaped like a camellia flower with pearl floral detail.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_22_camellia_flower.jpg",
        "stock": 34,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-022-ring-22-camellia-flower",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 322,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Solid Gold Marquise Diamond Bezel Ring, Minimalist Pinky Dome Statement Piece",
        "price": 260.66,
        "description": "14K solid gold bezel-set marquise diamond pinky ring, minimalist dome statement design.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_23_marquise_bezel.jpg",
        "stock": 35,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-023-ring-23-marquise-bezel",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 323,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K Gold Ring, Vintage Statement Ring, Elegant Stacking Jewelry, Luxury Fashion Accessory",
        "price": 99.99,
        "description": "18K gold vintage-style statement ring, elegant stacking fashion accessory.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_24_vintage_statement.jpg",
        "stock": 36,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-024-ring-24-vintage-statement",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 324,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "10K & 14K Gold Fiori Hibiscus Flower Ring",
        "price": 154.34,
        "description": "Solid 10K/14K gold ring shaped as a hibiscus flower, fine floral jewelry.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_25_hibiscus_flower.jpg",
        "stock": 37,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-025-ring-25-hibiscus-flower",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 325,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "1 CT IGI Certified Lab Grown Diamond Engagement Ring, Solid Gold, Oval Cut, 3/4 Eternity Twisted Ring",
        "price": 442.31,
        "description": "Solid gold engagement ring with a 1ct IGI-certified oval-cut lab-grown diamond in a twisted 3/4 eternity band.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_26_igi_lab_diamond.jpg",
        "stock": 38,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-026-ring-26-igi-lab-diamond",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 326,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Engraved Initial Name Ring, Dainty Gold Open Ring, Adjustable Minimalist Band",
        "price": 21.55,
        "description": "Dainty gold-plated adjustable open ring with an engraved initial, minimalist design.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_27_engraved_initial_open.jpg",
        "stock": 39,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-027-ring-27-engraved-initial-open",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 327,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Opal Moon Ring, Adjustable, Dainty Open Ring, Celestial Jewelry, October Birthstone Gift",
        "price": 19.99,
        "description": "Adjustable open ring with an opal moon design, celestial-themed October birthstone jewelry.",
        "category": "Jewelry",
        "subcategory": "Rings",
        "image": "/Jewelry%20Catalog/images/ring_28_opal_moon.jpg",
        "stock": 40,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-028-ring-28-opal-moon",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 328,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Real 14K Solid Gold Rope Chain Necklace For Women, Thin Twisted Link Pendant Necklace",
        "price": 81.5,
        "description": "Real 14K solid gold rope chain necklace, thin twisted-link design available in 0.7mm-1.2mm widths. Minimalist everyday jewelry.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_01_rope_chain.jpg",
        "stock": 41,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-029-necklace-01-rope-chain",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 329,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Custom Name Necklace, 18K Gold Plated Name Necklace, Personalized Cursive Name Jewelry",
        "price": 14.08,
        "description": "18K gold-plated personalized name necklace in cursive script. Popular birthday/Christmas gift.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_02_custom_name.jpg",
        "stock": 42,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-030-necklace-02-custom-name",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 330,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Diamond Solitaire Pendant: Lab Grown 0.10ct VVS1, 14K Gold Prong Setting",
        "price": 214.21,
        "description": "14K gold pendant necklace with a 0.10ct VVS1 lab-grown diamond solitaire in a classic prong setting.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_03_diamond_solitaire_pendant.jpg",
        "stock": 43,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-031-necklace-03-diamond-solitaire-pendant",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 331,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "10K Gold Cuban Curb Chain Necklace, Real Gold Curb Chain, Unisex Cuban Link Chain",
        "price": 262.5,
        "description": "Real 10K solid gold Cuban curb link chain, unisex design, everyday statement chain.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_04_cuban_curb_chain.jpg",
        "stock": 44,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-032-necklace-04-cuban-curb-chain",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 332,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Personalized Heart Locket Necklace, Love Locket with Photo, Tiny Gold Heart Locket",
        "price": 19.06,
        "description": "Tiny gold-tone heart locket necklace that opens to hold a photo. Marketed as a memorial/best-friend gift.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_05_heart_locket.jpg",
        "stock": 45,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-033-necklace-05-heart-locket",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 333,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Gold Evil Eye Necklace, Sapphire and Diamond Eye Pendant, Dainty Protection Necklace",
        "price": 54,
        "description": "14K gold handmade evil-eye pendant necklace set with sapphire and diamond accents, dainty spiritual/protection jewelry.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_06_evil_eye.jpg",
        "stock": 46,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-034-necklace-06-evil-eye",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 334,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Gold Cuban Link Chain Necklace with Bezel Setting Solitaire Diamond, 3MM Curb Link, by Ferkos Fine Jewelry",
        "price": 1360,
        "description": "Luxury 14K solid gold Cuban link chain necklace with a bezel-set solitaire diamond, 3mm curb link, by Ferkos Fine Jewelry.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_07_cuban_link_diamond_luxury.jpg",
        "stock": 47,
        "source": "Verified Jewelry Supplier",
        "supplierName": "FerkosFineJewelry",
        "sourceProductId": "jewelry-035-necklace-07-cuban-link-diamond-luxury",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 335,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Lab Grown Diamond Solitaire Necklace, Gold Necklace With Diamond, Diamond Necklace for Bridal",
        "price": 399,
        "description": "14K gold minimalist bridal necklace with a lab-grown diamond solitaire pendant, wedding jewelry style.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_08_diamond_solitaire.jpg",
        "stock": 48,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-036-necklace-08-diamond-solitaire",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 336,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K Gold Filled Chain Necklace, Pearl Chain, Curb Chain, Box Chain, Paperclip Chain, Dainty Chain",
        "price": 11.99,
        "description": "18K gold-filled chain necklace, available in pearl, curb, box, paperclip or twist chain styles.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_09_pearl_curb_chain.jpg",
        "stock": 49,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-037-necklace-09-pearl-curb-chain",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 337,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Personalized Name Necklace, Custom 18K Gold Plated Name Necklace, Minimalist",
        "price": 13.95,
        "description": "18K gold-plated minimalist personalized name necklace, popular Mother's Day/Christmas gift.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_10_personalized_name.jpg",
        "stock": 50,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-038-necklace-10-personalized-name",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 338,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Dainty Freshwater Pearl Necklace with Diamond, Gold Leaf Diamond Pearl Necklace, Bridal Necklace",
        "price": 21.1,
        "description": "Dainty gold-tone necklace combining a freshwater pearl and diamond-style leaf accent, bridal/bridesmaid style.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_11_pearl_diamond.jpg",
        "stock": 12,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-039-necklace-11-pearl-diamond",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 339,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Lab Grown Diamond, 14K Gold Attached Diamond Solitaire Necklace, Beautiful White Diamonds",
        "price": 257.39,
        "description": "14K gold necklace with a lab-grown diamond solitaire pendant permanently attached to the chain.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_12_diamond_attached_solitaire.jpg",
        "stock": 13,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-040-necklace-12-diamond-attached-solitaire",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 340,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "0.5ct Oval Diamond Necklace, 14K Yellow Gold, Dainty Minimalist Oval Pendant",
        "price": 177.5,
        "description": "14K yellow gold dainty necklace with a 0.5ct real oval diamond pendant.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_13_oval_diamond.jpg",
        "stock": 14,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-041-necklace-13-oval-diamond",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 341,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Gold Rope Chain Necklace, 2mm-6mm, 18-26 inches, Men Women",
        "price": 283.2,
        "description": "Solid 14K gold rope chain necklace available in multiple widths and lengths, unisex.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_14_rope_chain_thick.jpg",
        "stock": 15,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-042-necklace-14-rope-chain-thick",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 342,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "10K Yellow Gold Figaro Chain Necklace, 2mm-6.6mm, 16-28 inch, Thick Link Chain",
        "price": 153.73,
        "description": "Real 10K yellow gold thick Figaro link chain necklace, unisex, multiple sizes.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_15_figaro_chain.jpg",
        "stock": 16,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-043-necklace-15-figaro-chain",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 343,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Pear Cut Moissanite Solitaire Pendant Necklace, 14K Gold Plated Teardrop Charm",
        "price": 67.83,
        "description": "14K gold-plated teardrop necklace featuring a pear-cut moissanite solitaire.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_16_moissanite_teardrop.jpg",
        "stock": 17,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-044-necklace-16-moissanite-teardrop",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 344,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Dainty Opal Necklace, 14K Gold Vermeil Sterling Silver, October Birthstone Jewelry",
        "price": 32.27,
        "description": "14K gold vermeil sterling silver necklace with a dainty opal pendant, October birthstone gift.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_17_opal_vermeil.jpg",
        "stock": 18,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-045-necklace-17-opal-vermeil",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 345,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Dainty Natural Freshwater Pearl Necklace, Gold Chain Pearl Necklace, Pearl Choker",
        "price": 21.95,
        "description": "Gold chain necklace with multiple natural freshwater pearls, wearable as a choker.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_18_pearl_choker.jpg",
        "stock": 19,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-046-necklace-18-pearl-choker",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 346,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Birth Month Flower Necklace, Pressed Floral Pendant, Gold Stainless Steel Chain",
        "price": 32,
        "description": "Gold stainless steel necklace with a real pressed birth-month flower sealed in a pendant.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_19_birth_flower_pressed.jpg",
        "stock": 20,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-047-necklace-19-birth-flower-pressed",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 347,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Solid 14K Gold Wheat Diamond Cut Sparkle Chain, Italian Made",
        "price": 275,
        "description": "Solid 14K Italian-made gold wheat chain with diamond-cut sparkle finish, ladies' style.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_20_wheat_chain_italian.jpg",
        "stock": 21,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-048-necklace-20-wheat-chain-italian",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 348,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Green Cat Eye Stone Necklace in Gold, Vintage Style Amulet Pendant, Waterproof",
        "price": 46.8,
        "description": "Waterproof, tarnish-free gold necklace with a vintage-style green cat's-eye stone amulet pendant.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_21_cat_eye_stone.jpg",
        "stock": 22,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-049-necklace-21-cat-eye-stone",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 349,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K Gold Ankh Cross Necklace, Egyptian Jewelry, Key of Life Pendant, Spiritual Protection Necklace",
        "price": 20.09,
        "description": "18K gold-plated Ankh cross pendant necklace, Egyptian-inspired spiritual jewelry.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_22_ankh_cross.jpg",
        "stock": 23,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-050-necklace-22-ankh-cross",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 350,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Minimalist Freshwater Pearl Drop Necklace, Single Pearl Necklace, Wedding/Bridal Jewelry",
        "price": 27.99,
        "description": "Minimalist gold necklace with a single freshwater pearl drop, bridal/bridesmaid gift style.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_23_pearl_drop.jpg",
        "stock": 24,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-051-necklace-23-pearl-drop",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 351,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K Gold Plated Chunky Chain Statement Necklace, Bold Layered Choker",
        "price": 38.93,
        "description": "18K gold-plated bold chunky chain statement choker necklace, hypoallergenic.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_24_chunky_statement.jpg",
        "stock": 25,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-052-necklace-24-chunky-statement",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 352,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Multiple Name Necklace, 14K Gold Name Necklace, Family Name Necklace, Kids Name Necklace",
        "price": 16.5,
        "description": "14K gold-plated necklace personalized with multiple family/kids' names.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_25_multiple_name.jpg",
        "stock": 26,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-053-necklace-25-multiple-name",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 353,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Gold Butterfly Necklace",
        "price": 375,
        "description": "Solid gold butterfly pendant necklace, fine jewelry piece.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_26_butterfly.jpg",
        "stock": 27,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-054-necklace-26-butterfly",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 354,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Solid Gold Dainty Heart Necklace, Minimalist Sacred Heart Pendant Necklace",
        "price": 213.2,
        "description": "14K solid gold minimalist sacred-heart pendant necklace, Valentine's/love gift.",
        "category": "Jewelry",
        "subcategory": "Necklaces",
        "image": "/Jewelry%20Catalog/images/necklace_27_sacred_heart.jpg",
        "stock": 28,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-055-necklace-27-sacred-heart",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 355,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K Gold Huggie Hoops, Dainty CZ Studs Diamond Earring Set, Cartilage Piercings, Stacking Earrings",
        "price": 24.7,
        "description": "18K gold-plated huggie hoop earring set with dainty CZ studs, designed for stacking and cartilage piercings.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_01_huggie_hoops_cz.jpg",
        "stock": 29,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-056-earring-01-huggie-hoops-cz",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 356,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Solid Gold Ball Stud Earrings, Classic Round Ball Studs, Secure Butterfly Pushbacks, by TILO Jewelry",
        "price": 48.99,
        "description": "14K solid gold classic round ball stud earrings with secure butterfly pushbacks, available in 3mm-8mm sizes.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_02_ball_studs.jpg",
        "stock": 30,
        "source": "Verified Jewelry Supplier",
        "supplierName": "TILO Jewelry",
        "sourceProductId": "jewelry-057-earring-02-ball-studs",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 357,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Gold Hoops, Teardrop Hoop Earrings, Tapered Hoops, Teardrop Huggie Earrings, Gold Gypsy Earrings",
        "price": 588,
        "description": "14K solid gold teardrop-shaped tapered hoop earrings in a gypsy style.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_03_teardrop_hoops.jpg",
        "stock": 31,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-058-earring-03-teardrop-hoops",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 358,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "10K & 14K Solid Gold Nugget Round Circle Minimalist Push Back Stud Earrings, Unisex",
        "price": 101.84,
        "description": "Solid 10K/14K gold nugget-textured round circle stud earrings with push backs, unisex minimalist design.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_04_nugget_studs_unisex.jpg",
        "stock": 32,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier (made in USA)",
        "sourceProductId": "jewelry-059-earring-04-nugget-studs-unisex",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 359,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Solid Gold Moissanite Stud Earrings, 4-Prong Solitaire",
        "price": 73.5,
        "description": "14K solid gold stud earrings featuring 4-prong solitaire moissanite stones.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_05_moissanite_studs.jpg",
        "stock": 33,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-060-earring-05-moissanite-studs",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 360,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Diamond Pearl Earrings, Simple Freshwater Pearl Earrings, Gold Hoop Earrings, Bridal Jewelry",
        "price": 28.99,
        "description": "Gold hoop earrings with freshwater pearl and diamond accents, marketed as everyday elegant/bridal jewelry.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_06_pearl_diamond_hoops.jpg",
        "stock": 34,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-061-earring-06-pearl-diamond-hoops",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 361,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Vintage 1990s 14 Ct Rolled Gold Ruby Earrings, Hallmarked 585 RG",
        "price": 100.17,
        "description": "Vintage 1990s rolled gold earrings set with ruby stones, hallmarked 585 RG (14ct rolled gold).",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_07_vintage_ruby.jpg",
        "stock": 35,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-062-earring-07-vintage-ruby",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 362,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Star Diamond Hoop Earrings, Dainty North Star Huggie Earrings, Celestial Earrings",
        "price": 21.95,
        "description": "Dainty gold huggie hoop earrings with a small star/celestial diamond accent design.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_08_star_diamond_huggie.jpg",
        "stock": 36,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-063-earring-08-star-diamond-huggie",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 363,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K Gold Filled Oval CZ Drop Earrings, Solitaire Huggie Hoops, Sparkling Dangle Earrings, Dainty Bridal Jewelry",
        "price": 20.79,
        "description": "18K gold-filled oval CZ drop earrings on huggie hoops, dainty bridal-style sparkle.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_09_oval_cz_drop.jpg",
        "stock": 37,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-064-earring-09-oval-cz-drop",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 364,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Pair of Gold Hoop Earrings, 20mm-80mm, Large Hoop Gold Earrings, XL Hoop, Over Size",
        "price": 25.17,
        "description": "Trending oversized gold hoop earrings available from 20mm up to 80mm.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_10_xl_hoops.jpg",
        "stock": 38,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-065-earring-10-xl-hoops",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 365,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Vintage 1990s 14 Ct Rolled Gold Amethyst Earrings, Hallmarked 585 RG",
        "price": 107.36,
        "description": "Vintage 1990s rolled gold earrings set with amethyst stones, hallmarked 585 RG.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_11_vintage_amethyst.jpg",
        "stock": 39,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-066-earring-11-vintage-amethyst",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 366,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Certified VVS1 Moissanite Earrings, Screw Back, Round Cut Studs, 925 Sterling Silver",
        "price": 40.13,
        "description": "925 sterling silver screw-back stud earrings with certified VVS1 moissanite, ethically sourced.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_12_vvs1_moissanite_screwback.jpg",
        "stock": 40,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-067-earring-12-vvs1-moissanite-screwback",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 367,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Interlocking Knot Gold Earrings, 18K Twisted Rope Hoops",
        "price": 16.39,
        "description": "18K gold-plated twisted rope hoop earrings with an interlocking knot design.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_13_interlocking_knot.jpg",
        "stock": 41,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-068-earring-13-interlocking-knot",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 368,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Mother of Pearl Flower Hoop Earrings, Dainty Floral Pearl Hoop Earrings, Bridal Earrings",
        "price": 18.21,
        "description": "Gold huggie hoop earrings with a dainty mother-of-pearl flower detail, bridal/bridesmaid gift.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_14_mother_of_pearl_hoop.jpg",
        "stock": 42,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-069-earring-14-mother-of-pearl-hoop",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 369,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Greek Key Hoop Earrings in 14K Solid Gold, Lightweight Everyday Huggie Hoops",
        "price": 187.5,
        "description": "14K solid gold huggie hoop earrings featuring a classic Greek key pattern.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_15_greek_key_hoop.jpg",
        "stock": 43,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-070-earring-15-greek-key-hoop",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 370,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Blue Sapphire Gold Hoop Earrings, 14K Gold Vermeil, Genuine Lab Sapphire, September Birthstone",
        "price": 107.07,
        "description": "14K gold vermeil hoop earrings set with genuine lab sapphire, September birthstone gift.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_16_sapphire_hoop.jpg",
        "stock": 44,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-071-earring-16-sapphire-hoop",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 371,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Classic Opal Huggie Hoop Earrings, 18K Gold, Dainty Opal Jewelry, Daily Hoop Earrings",
        "price": 26.19,
        "description": "18K gold huggie hoop earrings with dainty opal stones for daily wear.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_17_opal_huggie.jpg",
        "stock": 45,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-072-earring-17-opal-huggie",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 372,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Filigree Solid 14K Gold Dangle Earrings, Victorian Earrings",
        "price": 564,
        "description": "Solid 14K gold Victorian-style filigree dangle earrings, fine handmade jewelry.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_18_filigree_victorian.jpg",
        "stock": 46,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-073-earring-18-filigree-victorian",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 373,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "3.00ct Oval Lab Grown Diamond Hoop Earrings, 14K Solid Gold Huggies, E VS Clarity Certified",
        "price": 739.6,
        "description": "14K solid gold huggie hoops set with 3.00ct total oval lab-grown diamonds, E color VS clarity certified.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_19_oval_lab_diamond_hoop.jpg",
        "stock": 47,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-074-earring-19-oval-lab-diamond-hoop",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 374,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Leaf Peridot Earrings, 24K Gold Vermeil Sterling Silver, Handmade Jewelry",
        "price": 86.25,
        "description": "24K gold vermeil sterling silver leaf-shaped earrings set with peridot stones.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_20_leaf_peridot.jpg",
        "stock": 48,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-075-earring-20-leaf-peridot",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 375,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Custom Name Earrings, Twist Hoop Earrings, Hoop Name Earrings, Drop Name Earrings",
        "price": 23.24,
        "description": "Personalized twist hoop earrings customized with a name, drop-style design.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_21_custom_name_twist.jpg",
        "stock": 49,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-076-earring-21-custom-name-twist",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 376,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Rose Gold Earrings, Pear Cut Diamond Hoop Earrings, 0.8ct E/VVS2 Lab Created Diamond",
        "price": 692.5,
        "description": "14K rose gold hoop earrings featuring pear-cut lab-created diamonds, 0.8ct total, E/VVS2 grade.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_22_rose_gold_pear_diamond.jpg",
        "stock": 50,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-077-earring-22-rose-gold-pear-diamond",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 377,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Gold Baroque Pearl Drop Earrings, Minimalist Freshwater Pearls Earrings, Wedding/Bridal Earrings",
        "price": 21.04,
        "description": "Gold-tone drop earrings with baroque freshwater pearls, minimalist bridal style.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_23_baroque_pearl_drop.jpg",
        "stock": 12,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-078-earring-23-baroque-pearl-drop",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 378,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Raw Aquamarine Gold Earring, 14K Gold Earring, Dangle Earring, Blue Gemstone, July Birthstone",
        "price": 26.16,
        "description": "14K gold dangle earrings featuring raw aquamarine gemstones, July birthstone gift.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_24_raw_aquamarine.jpg",
        "stock": 13,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-079-earring-24-raw-aquamarine",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 379,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Ruby Gold Hoop Earrings, 14K Gold Vermeil, Genuine Lab Ruby Vintage Earring, Birthstone Gift",
        "price": 110.45,
        "description": "14K gold vermeil hoop earrings set with genuine lab ruby, vintage-inspired birthstone jewelry.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_25_ruby_hoop_vermeil.jpg",
        "stock": 14,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-080-earring-25-ruby-hoop-vermeil",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 380,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Gold Hoops, 14K Chunky Gold Huggies, Everyday Earrings, Solid Gold Hoops, 13mm/15mm",
        "price": 275,
        "description": "14K solid gold chunky huggie hoop earrings for everyday wear, available in 13mm or 15mm.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_26_chunky_huggies.jpg",
        "stock": 15,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-081-earring-26-chunky-huggies",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 381,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Tiny Peridot Earrings, 14K Gold Vermeil Marquise Studs, August Birthstone Jewelry",
        "price": 28.18,
        "description": "14K gold vermeil marquise stud earrings with tiny peridot stones, August birthstone gift.",
        "category": "Jewelry",
        "subcategory": "Earrings",
        "image": "/Jewelry%20Catalog/images/earring_27_tiny_peridot_marquise.jpg",
        "stock": 16,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-082-earring-27-tiny-peridot-marquise",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 382,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Gold Bracelet Women, Handmade Bracelet 14K Gold Fill Bangle, Wire Wrap Bracelet",
        "price": 149.95,
        "description": "Handmade 14K gold-fill wire-wrapped bangle bracelet for women.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_01_handmade_bangle_wirewrap.jpg",
        "stock": 17,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-083-bracelet-01-handmade-bangle-wirewrap",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 383,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Waterproof 18K Gold Flower Bracelet, Dainty Diamond Clover Chain, Floral Charm Bracelet",
        "price": 35.17,
        "description": "Waterproof 18K gold-plated bracelet with a dainty diamond clover/flower charm chain.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_02_flower_clover_chain.jpg",
        "stock": 18,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-084-bracelet-02-flower-clover-chain",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 384,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Solid Gold Bismark Chain Bracelet, Stacked Curb Link, Bismarck Bracelet",
        "price": 227.62,
        "description": "14K solid gold Bismark-style stacked curb link chain bracelet.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_03_bismark_chain.jpg",
        "stock": 19,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-085-bracelet-03-bismark-chain",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 385,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Gold Blue Sapphire Bracelet for Women, September Birthstone Gift, Dainty Diamond Style Chain",
        "price": 33.82,
        "description": "14K gold-plated dainty chain bracelet with blue sapphire stones, September birthstone gift.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_04_blue_sapphire.jpg",
        "stock": 20,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-086-bracelet-04-blue-sapphire",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 386,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K Solid Gold Four Leaf Clover Diamond Bracelet, Dainty Diamond Station Bracelet",
        "price": 288,
        "description": "18K solid gold bracelet with four-leaf clover diamond stations, fine jewelry gift.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_05_four_leaf_clover_diamond.jpg",
        "stock": 21,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-087-bracelet-05-four-leaf-clover-diamond",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 387,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K GL Solid Curb Link Yellow Gold Bracelet with Filigree Heart Padlock",
        "price": 111.06,
        "description": "18K gold curb link bracelet featuring a filigree heart padlock charm.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_06_curb_filigree_padlock.jpg",
        "stock": 22,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-088-bracelet-06-curb-filigree-padlock",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 388,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Gold Heart Charm Bracelet, Snake Chain for Women",
        "price": 24.46,
        "description": "Gold-tone snake chain bracelet with a heart charm, gift jewelry.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_07_heart_charm_snake.jpg",
        "stock": 23,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-089-bracelet-07-heart-charm-snake",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 389,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "24K Solid Gold Pixiu Bracelet, Feng Shui Chinese Mythology Symbol of Wealth & Protection",
        "price": 79.61,
        "description": "24K solid gold Pixiu-charm bracelet, a Feng Shui symbol of wealth, prosperity and protection.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_08_pixiu_fengshui.jpg",
        "stock": 24,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-090-bracelet-08-pixiu-fengshui",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 390,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Diamond Cuban Link Bracelet, 14K Solid Gold, Dainty Minimalist Jewelry",
        "price": 1530,
        "description": "14K solid gold Cuban link bracelet set with diamonds, minimalist luxury piece.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_09_diamond_cuban_link.jpg",
        "stock": 25,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-091-bracelet-09-diamond-cuban-link",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 391,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Retro Charms Watch Bracelet, Gold Plated Pearl & Bead Charms Jewelry, Feminine Timepiece",
        "price": 14.92,
        "description": "Gold-plated retro-style wristwatch bracelet with pearl and bead charms.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_10_retro_watch_charms.jpg",
        "stock": 26,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-092-bracelet-10-retro-watch-charms",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 392,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K Solid Gold Double Row Faceted Bead Bracelet, AU750",
        "price": 259,
        "description": "18K solid gold double-row faceted bead bracelet, AU750 fine jewelry.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_11_double_row_bead.jpg",
        "stock": 27,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-093-bracelet-11-double-row-bead",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 393,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Round Pearl Bracelet with Diamond, Gold Leaf Diamond Bracelet, Dainty Pearl Bracelet, Bridal",
        "price": 19.3,
        "description": "Dainty gold-tone bracelet combining round pearls with diamond-style leaf accents, bridal style.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_12_pearl_diamond.jpg",
        "stock": 28,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-094-bracelet-12-pearl-diamond",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 394,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "BELLA 14K Solid Gold Ultra Dainty Bar Bracelet, Personalised Initial/Name/Roman Numerals",
        "price": 81.34,
        "description": "14K solid gold ultra-dainty bar bracelet, personalizable with initials, names, or roman numerals.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_13_bella_bar_initial.jpg",
        "stock": 29,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-095-bracelet-13-bella-bar-initial",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 395,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Bangle Bracelet by Sami Jewels, Minimalist Bracelet, Dainty Diamond Bangle Bracelet",
        "price": 78.4,
        "description": "Minimalist dainty diamond bangle bracelet by Sami Jewels, vintage-inspired.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_14_sami_bangle.jpg",
        "stock": 30,
        "source": "Verified Jewelry Supplier",
        "supplierName": "SamiJEWELS",
        "sourceProductId": "jewelry-096-bracelet-14-sami-bangle",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 396,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Personalized Italian Bracelet, Custom Gold Italy Charms, Gold Italian Charm Bracelet",
        "price": 13.99,
        "description": "Personalized Italian-style charm bracelet with custom gold Italy charms.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_15_italian_charm.jpg",
        "stock": 31,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-097-bracelet-15-italian-charm",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 397,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Minimalist Gold Stainless Steel Bangle Bracelet, Waterproof Stackable Everyday Jewelry",
        "price": 24.79,
        "description": "Waterproof gold stainless steel bangle bracelet, stackable everyday jewelry.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_16_stainless_bangle.jpg",
        "stock": 32,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-098-bracelet-16-stainless-bangle",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 398,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Gold ID Bracelet, Name Bar Bracelet, Solid Gold Cuban Link Bracelet, Personalized, Engraved Bar",
        "price": 705,
        "description": "14K solid gold Cuban link ID bracelet with a personalized engraved name bar.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_17_id_name_bar.jpg",
        "stock": 33,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-099-bracelet-17-id-name-bar",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 399,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "10K Real Gold Puffed Mariner Bracelet, 4.5mm-9mm, Yellow Gold",
        "price": 337.19,
        "description": "10K real yellow gold puffed mariner-link bracelet, available in multiple widths.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_18_puffed_mariner.jpg",
        "stock": 34,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-100-bracelet-18-puffed-mariner",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 400,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Gold Pink Sapphire Bracelet, Teardrop Station Chain, Fine Jewelry",
        "price": 325.5,
        "description": "14K gold teardrop station bracelet set with pink sapphire stones.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_19_pink_sapphire_station.jpg",
        "stock": 35,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-101-bracelet-19-pink-sapphire-station",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 401,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Gold Rose Ruby Bracelet, Simple Gold Chain Jewelry, Women's Mini Stackable Bracelet",
        "price": 29.71,
        "description": "14K gold-plated stackable bracelet with rose-cut ruby stones, minimalist chain design.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_20_rose_ruby.jpg",
        "stock": 36,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-102-bracelet-20-rose-ruby",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 402,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "14K Gold Lab Grown Diamond Bangle, 1.5 CT Lab Created Diamond Open Bangle",
        "price": 503.11,
        "description": "14K gold open bangle set with 1.5ct total lab-grown diamonds, elegant fine jewelry.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_21_lab_diamond_bangle.jpg",
        "stock": 37,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-103-bracelet-21-lab-diamond-bangle",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 403,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Gold Plated Bangle Bracelet, Simple Thin Gold Cuff Bracelet, Minimalist Charm Bangle",
        "price": 24.58,
        "description": "Gold-plated thin cuff-style bangle, stackable minimalist charm bracelet.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_22_pandora_bangle.jpg",
        "stock": 38,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-104-bracelet-22-pandora-bangle",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 404,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Minimalist Freshwater Pearl Bracelet with CZ Diamonds, 14K Gold-Plated, Bridal Bracelet",
        "price": 22.99,
        "description": "14K gold-plated bracelet combining freshwater pearls with CZ diamond accents, bridal style.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_23_pearl_cz.jpg",
        "stock": 39,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-105-bracelet-23-pearl-cz",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 405,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "18K Gold Clover Bracelet, Radiant Floral Charm Bracelet, Lucky Clover Chain Jewelry",
        "price": 43.57,
        "description": "18K gold-plated clover-charm bracelet, lucky floral motif, everyday elegant gift.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_24_clover_radiant.jpg",
        "stock": 40,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-106-bracelet-24-clover-radiant",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 406,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Custom Engraved Inspirational Bangle, 18K Gold Women's Bangle, DIY Engraved Name Bracelet",
        "price": 22.35,
        "description": "18K gold-plated bangle that can be custom engraved with a name or inspirational message.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_25_inspirational_engraved.jpg",
        "stock": 41,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-107-bracelet-25-inspirational-engraved",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 407,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Chunky Gold Chain Bracelet, Large Link Chain Bracelet, Gold Statement Bracelet",
        "price": 43.11,
        "description": "Chunky large-link gold statement chain bracelet, layering/stacking style.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_26_chunky_statement_chain.jpg",
        "stock": 42,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-108-bracelet-26-chunky-statement-chain",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 408,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Tennis Bracelet, Gold Tennis Bracelet, Cubic Zirconia Tennis Bracelet, Dainty Diamond Bracelet",
        "price": 56,
        "description": "Gold-plated tennis bracelet set with cubic zirconia stones, dainty everyday sparkle.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_27_tennis_cz.jpg",
        "stock": 43,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-109-bracelet-27-tennis-cz",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 409,
        "catalogVersion": CATALOG_VERSION
    },
    {
        "name": "Personalized Birthstone Beaded Bracelet, Gold Charm Bracelet, Custom 1-5 Birthstones",
        "price": 22.5,
        "description": "Gold-tone beaded charm bracelet personalized with 1-5 custom birthstones, gift for mom/wife/daughter.",
        "category": "Jewelry",
        "subcategory": "Bracelets",
        "image": "/Jewelry%20Catalog/images/bracelet_28_birthstone_beaded.jpg",
        "stock": 44,
        "source": "Verified Jewelry Supplier",
        "supplierName": "Jewelry Supplier",
        "sourceProductId": "jewelry-110-bracelet-28-birthstone-beaded",
        "isFeatured": false,
        "isPromoted": false,
        "sortOrder": 410,
        "catalogVersion": CATALOG_VERSION
    }
];

export const products = [
    ...starterProducts,
    ...massageProducts,
    ...jewelryProducts,
];

// Quick lookup: product name to local image path
export const LOCAL_PRODUCT_IMAGES: Record<string, string> = Object.fromEntries(
    products.map(p => [p.name, p.image])
);

