// Catalog version - bump to force Firestore wipe and reseed
export const CATALOG_VERSION = 8;

const starterProducts = [
    {
        name: "Apple AirPods Pro (3rd Gen)",
        price: 74.7,
        description: "The latest Apple AirPods Pro with active noise cancellation, Adaptive Audio, and up to 30 hours total listening time.",
        category: "Audio",
        image: "/products/01_Apple_AirPods_Pro_3rd_Gen.png",
        isFeatured: true, isPromoted: true, sortOrder: 1, catalogVersion: 6,
    },
    {
        name: "Meta Quest 3 Advanced VR Headset",
        price: 75,
        description: "Meta's most powerful mixed reality headset. Full-color passthrough, next-gen chipset, and an expansive library of VR and MR experiences.",
        category: "Tech & Gadgets",
        image: "/products/02_Meta_Quest_3_Advanced_VR_Headset.png",
        isFeatured: true, isPromoted: true, sortOrder: 2, catalogVersion: 6,
    },
    {
        name: "Withings Body Scan Smart Scale",
        price: 89.7,
        description: "Advanced health tracking scale measuring weight, body composition, nerve activity, and vascular age. Sync with your smartphone for deep health insights.",
        category: "Health & Fitness",
        image: "/products/03_Withings_Body_Scan_Smart_Scale.png",
        isFeatured: true, isPromoted: true, sortOrder: 3, catalogVersion: 6,
    },
    {
        name: "Breville Barista Express Espresso Machine",
        price: 239.7,
        description: "All-in-one espresso machine with integrated conical burr grinder. Grind, dose, tamp, and extract cafe-quality espresso at home.",
        category: "Home & Kitchen",
        image: "/products/05_Breville_Barista_Express_Espresso_Machine.png",
        isFeatured: true, isPromoted: true, sortOrder: 5, catalogVersion: 6,
    },
    {
        name: "Shokz OpenRun Pro Bone Conduction Headphones",
        price: 27,
        description: "Premium open-ear headphones using bone conduction technology. Stay aware of your surroundings while enjoying high-quality audio outdoors.",
        category: "Audio",
        image: "/products/06_Shokz_OpenRun_Pro_Bone_Conduction_Headphones.png",
        isFeatured: true, isPromoted: true, sortOrder: 6, catalogVersion: 6,
    },
    {
        name: "Dyson Airwrap Multi-Styler Complete Long",
        price: 179.7,
        description: "The iconic multi-styler that curls, waves, smooths, and dries using Coanda airflow with no extreme heat. Includes attachments for all hair types.",
        category: "Beauty & Personal Care",
        image: "/products/07_Dyson_Airwrap_Multi_Styler_Complete_Long.png",
        isFeatured: true, isPromoted: true, sortOrder: 7, catalogVersion: 6,
    },
    {
        name: "Fujifilm Instax Mini EVO Instant Camera",
        price: 59.7,
        description: "Hybrid instant camera combining digital shooting with analog printing. 10 lens and film effects, app connectivity, and a premium retro design.",
        category: "Photography",
        image: "/products/08_Fujifilm_Instax_Mini_EVO_Instant_Camera.png",
        isFeatured: true, isPromoted: true, sortOrder: 8, catalogVersion: 6,
    },
    {
        name: "Philips Hue Smart Light Starter Kit",
        price: 59.7,
        description: "Transform your home lighting with smart LED bulbs and the Hue Bridge. Control millions of colors via app, voice, or schedule for any mood.",
        category: "Smart Home",
        image: "/products/09_Philips_Hue_Smart_Light_Starter_Kit.png",
        isFeatured: true, isPromoted: true, sortOrder: 9, catalogVersion: 6,
    },
    {
        name: "GoPro HERO12 Black Action Camera",
        price: 119.7,
        description: "5.3K video, HyperSmooth 6.0 stabilization, and unlimited cloud backup. Waterproof to 33ft out of the box. The ultimate action camera for creators.",
        category: "Photography",
        image: "/products/10_GoPro_HERO12_Black_Action_Camera.png",
        isFeatured: true, isPromoted: true, sortOrder: 10, catalogVersion: 6,
    },
    {
        name: "Sonos Era 100 Smart Speaker",
        price: 74.7,
        description: "Premium stereo smart speaker with Trueplay tuning, Bluetooth, and Wi-Fi. Works with Alexa, Google Assistant, and Apple AirPlay 2.",
        category: "Audio",
        image: "/products/11_Sonos_Era_100_Smart_Speaker.png",
        isFeatured: true, isPromoted: true, sortOrder: 11, catalogVersion: 6,
    },
    {
        name: "Samsung T9 Portable SSD (2TB)",
        price: 53.7,
        description: "Blazing-fast 2TB portable SSD with USB 3.2 Gen 2x2 speeds up to 2,000 MB/s. Rugged, IP65-rated, and compact for on-the-go creators.",
        category: "Tech & Gadgets",
        image: "/products/12_Samsung_T9_Portable_SSD_2TB.png",
        isFeatured: true, isPromoted: true, sortOrder: 12, catalogVersion: 6,
    },
    {
        name: "Amazon Kindle Paperwhite Bundle",
        price: 28.5,
        description: "Kindle Paperwhite with premium fabric cover and 3-month Kindle Unlimited. 300 ppi glare-free display, waterproof, up to 10 weeks battery life.",
        category: "Tech & Gadgets",
        image: "/products/Extra_Amazon_Kindle_Paperwhite_Bundle.png",
        isFeatured: true, isPromoted: true, sortOrder: 13, catalogVersion: 6,
    },
    {
        name: "Apple AirPods Pro 2nd Gen MagSafe USB-C",
        price: 68.7,
        description: "Active Noise Cancellation, Adaptive Transparency, and Personalized Spatial Audio. MagSafe charging case with USB-C and up to 30 hours total listening time.",
        category: "Audio",
        image: "/products/Extra_Apple_AirPods_Pro_2nd_Generation_MagSafe_USB_C.png",
        isFeatured: true, isPromoted: true, sortOrder: 14, catalogVersion: 6,
    },
    {
        name: "Beats Studio Pro Wireless Headphones",
        price: 104.7,
        description: "Professional over-ear headphones with active noise cancelling, lossless audio via USB-C, and up to 40 hours battery life. Works with Apple and Android.",
        category: "Audio",
        image: "/products/Extra_Beats_Studio_Pro_Wireless_Headphones.png",
        isFeatured: true, isPromoted: true, sortOrder: 15, catalogVersion: 6,
    },
    {
        name: "Breville Barista Express With Box",
        price: 254.7,
        description: "The complete Breville Barista Express bundle with everything needed to pull cafe-quality espresso shots at home, fresh from the integrated grinder.",
        category: "Home & Kitchen",
        image: "/products/Extra_Breville_Barista_Express_Espresso_Machine_With_Box.png",
        isFeatured: true, isPromoted: true, sortOrder: 16, catalogVersion: 6,
    },
    {
        name: "DJI Mavic 3 Fly More Combo",
        price: 659.7,
        description: "Professional drone with Hasselblad camera, 46-min flight time, and 15km transmission. Includes extra batteries, charging hub, and carry bag.",
        category: "Photography",
        image: "/products/Extra_DJI_Mavic_3_Fly_More_Combo.png",
        isFeatured: true, isPromoted: true, sortOrder: 17, catalogVersion: 6,
    },
    {
        name: "Dyson V15 Detect Cordless Vacuum",
        price: 224.7,
        description: "Most powerful Dyson cordless vacuum with laser dust detection, dynamic load sensor, and 60-min run time. Reveals microscopic dust invisible to the naked eye.",
        category: "Home & Kitchen",
        image: "/products/Extra_Dyson_V15_Detect_Cordless_Vacuum.png",
        isFeatured: true, isPromoted: true, sortOrder: 18, catalogVersion: 6,
    },
    {
        name: "Garmin Forerunner 965 Smartwatch",
        price: 179.7,
        description: "Premium GPS running smartwatch with AMOLED display, full-color maps, training readiness score, and up to 23 days battery life.",
        category: "Health & Fitness",
        image: "/products/Extra_Garmin_Forerunner_965_Smartwatch.png",
        isFeatured: true, isPromoted: true, sortOrder: 19, catalogVersion: 6,
    },
    {
        name: "Instant Pot Duo 7-in-1 Electric Pressure Cooker",
        price: 29.7,
        description: "The world's best-selling multi-cooker. Pressure cook, slow cook, rice cook, steam, saute, make yogurt, and keep warm all in one appliance.",
        category: "Home & Kitchen",
        image: "/products/Extra_Instant_Pot_Duo_7_in_1_Electric_Pressure_Cooker.png",
        isFeatured: true, isPromoted: true, sortOrder: 20, catalogVersion: 6,
    },
    {
        name: "JBL Live Pro 2 Earbuds",
        price: 44.7,
        description: "True adaptive noise cancelling earbuds with Smart Ambient mode, 40-hour total battery, and 6-mic TrueVoice call technology. JBL Signature Sound with EQ.",
        category: "Audio",
        image: "/products/Extra_JBL_Live_Pro_2_Earbuds.png",
        isFeatured: true, isPromoted: true, sortOrder: 21, catalogVersion: 6,
    },
    {
        name: "75W Box Mod Vape Kit with Sub-Ohm Tank",
        price: 9,
        description: "Rechargeable 75W regulated box mod kit with adjustable wattage, OLED display, and sub-ohm tank. Single 18650 external battery (not included). Supports Variable Wattage, Bypass, Temperature Control (Ni/Ti/SS), and TCR modes. Wattage range 1–75W, resistance range 0.05–3.5O, temp range 100–315°C. 510-thread connection, USB-C charging. Kit includes: 75W mod, sub-ohm tank (2–4ml), 0.3O & 0.5O coils, USB cable, and user manual. Zinc alloy & stainless steel build. Dimensions: ~45 × 23 × 70.5mm.",
        category: "Vapes & E-Cigarettes",
        image: "/products/vapekit.jpg",
        isFeatured: true, isPromoted: true, sortOrder: 22, catalogVersion: 6,
    },
];

const wellnessCatalog = [
    ["CeraVe-Style Hydrating Facial Cleanser", 18.99, "Gentle daily facial cleanser for normal to dry skin with a non-stripping cream texture and reseller-friendly demand.", "Skin Care"],
    ["Foaming Facial Cleanser for Oily Skin", 16.99, "Everyday foaming cleanser designed for oily and combination skin routines.", "Skin Care"],
    ["Vitamin C Brightening Face Serum", 24.99, "Popular brightening serum format for morning skincare routines and glow-focused bundles.", "Skin Care"],
    ["Hyaluronic Acid Hydration Serum", 19.99, "Lightweight hydration serum for plumping, layering, and everyday moisture support.", "Skin Care"],
    ["Niacinamide 10% Blemish Serum", 17.99, "High-demand niacinamide serum style for pores, uneven tone, and blemish-prone skin routines.", "Skin Care"],
    ["Retinol Night Renewal Serum", 29.99, "Night serum format for anti-aging routines, texture care, and premium skincare bundles.", "Skin Care"],
    ["SPF 50 Daily Face Sunscreen", 21.99, "Daily facial sunscreen product type with broad reseller appeal across US and European markets.", "Skin Care"],
    ["Oil-Free Gel Moisturizer", 18.99, "Lightweight gel moisturizer for oily and combination skin routines.", "Skin Care"],
    ["Barrier Repair Face Cream", 26.99, "Rich cream format for dry skin, post-treatment care, and barrier support routines.", "Skin Care"],
    ["Under Eye Caffeine Serum", 15.99, "Caffeine eye serum product type for morning skincare and tired-eye routines.", "Skin Care"],
    ["AHA BHA Exfoliating Toner", 22.99, "Exfoliating toner format for texture, pores, and glow-focused skincare routines.", "Skin Care"],
    ["Micellar Cleansing Water", 12.99, "Popular makeup-removing cleansing water for daily skincare and beauty bundles.", "Skin Care"],
    ["Cleansing Balm Makeup Remover", 23.99, "Soft balm cleanser format for double-cleansing routines and beauty resellers.", "Skin Care"],
    ["Hydrocolloid Acne Patch Pack", 9.99, "Fast-moving acne patch pack for teen, beauty, and skincare stores.", "Skin Care"],
    ["Clay Pore Detox Face Mask", 14.99, "Clay mask product type for oily skin, pores, and weekly skincare routines.", "Skin Care"],
    ["Sheet Mask Variety Pack", 19.99, "Multi-pack sheet mask bundle for hydration, glow, and impulse beauty sales.", "Skin Care"],
    ["Rose Water Facial Toner", 13.99, "Refreshing toner format for daily skincare routines and beauty bundles.", "Skin Care"],
    ["Peptide Firming Face Cream", 32.99, "Premium peptide cream product type for anti-aging skincare shoppers.", "Skin Care"],
    ["Ceramide Moisturizing Lotion", 20.99, "Everyday lotion format for face and body moisture routines.", "Skin Care"],
    ["Lip Repair Balm Multipack", 8.99, "Small-format lip balm pack with strong repeat-purchase potential.", "Skin Care"],
    ["Body Retinol Smoothing Lotion", 24.99, "Trending body lotion format for texture, bumps, and evening body care routines.", "Skin Care"],
    ["Hand Cream Travel Set", 11.99, "Portable hand cream bundle for personal care, gifting, and checkout add-ons.", "Skin Care"],
    ["Body Wash Sensitive Skin", 15.99, "Gentle body wash product type for daily personal care resale.", "Skin Care"],
    ["Tea Tree Blemish Spot Gel", 10.99, "Spot treatment format for blemish-prone skin and compact skincare bundles.", "Skin Care"],
    ["Snail Mucin Hydrating Essence", 21.99, "K-beauty style essence for hydration-focused routines and viral skincare shoppers.", "Skin Care"],
    ["Centella Soothing Cream", 18.99, "Soothing cream format for sensitive skin and barrier care routines.", "Skin Care"],
    ["Mineral Sunscreen Stick SPF 50", 16.99, "Portable sunscreen stick format for travel, sports, and family skincare.", "Skin Care"],
    ["Glycolic Acid Resurfacing Pads", 19.99, "Exfoliating pad format for glow, texture, and weekly skincare routines.", "Skin Care"],
    ["Facial Oil with Squalane", 22.99, "Light facial oil format for dry skin routines and premium beauty bundles.", "Skin Care"],
    ["Benzoyl Peroxide Acne Wash", 13.99, "Acne wash product type for blemish-prone skincare shoppers.", "Skin Care"],
    ["Calcium 600 mg Tablets", 14.99, "Popular calcium supplement format for bone-health wellness categories. Not a prescription medicine.", "Supplements & Wellness"],
    ["Calcium Magnesium Zinc Tablets", 17.99, "Mineral blend supplement style for daily wellness and bone support categories.", "Supplements & Wellness"],
    ["Vitamin D3 2000 IU Softgels", 12.99, "High-demand vitamin D3 softgel format for everyday supplement resellers.", "Supplements & Wellness"],
    ["Vitamin D3 K2 Capsules", 19.99, "Premium D3 plus K2 supplement format for wellness stores.", "Supplements & Wellness"],
    ["Magnesium Glycinate Capsules", 18.99, "Popular magnesium glycinate capsule format for relaxation and wellness routines.", "Supplements & Wellness"],
    ["Magnesium Citrate Powder", 16.99, "Powdered magnesium format for wellness, digestion, and evening routines.", "Supplements & Wellness"],
    ["Omega-3 Fish Oil Softgels", 21.99, "Omega-3 softgel format with broad demand in supplement categories.", "Supplements & Wellness"],
    ["Krill Oil Omega-3 Softgels", 24.99, "Premium omega-3 krill oil style product for wellness shoppers.", "Supplements & Wellness"],
    ["Zinc 50 mg Tablets", 9.99, "Fast-moving zinc supplement format for everyday wellness stores.", "Supplements & Wellness"],
    ["Vitamin C 1000 mg Tablets", 11.99, "Popular vitamin C tablet format for immune-support wellness categories.", "Supplements & Wellness"],
    ["Vitamin C Gummies", 13.99, "Gummy supplement format for family wellness and easy daily routines.", "Supplements & Wellness"],
    ["Daily Multivitamin Tablets", 18.99, "General multivitamin product type with strong repeat-purchase potential.", "Supplements & Wellness"],
    ["Women's Multivitamin Gummies", 20.99, "Women's gummy multivitamin style product for wellness resale.", "Supplements & Wellness"],
    ["Men's Multivitamin Capsules", 20.99, "Men's multivitamin capsule format for daily wellness categories.", "Supplements & Wellness"],
    ["Probiotic 10 Billion CFU Capsules", 22.99, "Probiotic capsule format for digestive wellness and supplement bundles.", "Supplements & Wellness"],
    ["Prebiotic Fiber Gummies", 15.99, "Fiber gummy format for digestive wellness and repeat-purchase customers.", "Supplements & Wellness"],
    ["Collagen Peptides Powder", 29.99, "Collagen powder format for beauty, wellness, and fitness shoppers.", "Supplements & Wellness"],
    ["Marine Collagen Capsules", 24.99, "Marine collagen capsule product type for beauty-from-within routines.", "Supplements & Wellness"],
    ["Biotin 5000 mcg Gummies", 13.99, "Biotin gummy format for hair, skin, and nails supplement categories.", "Supplements & Wellness"],
    ["Iron 65 mg Tablets", 10.99, "Iron supplement product type for wellness catalogs. Use according to label directions.", "Supplements & Wellness"],
    ["Folic Acid 400 mcg Tablets", 8.99, "Folic acid supplement format for daily wellness categories.", "Supplements & Wellness"],
    ["Vitamin B12 Sublingual Tablets", 12.99, "B12 sublingual tablet format for energy-support wellness categories.", "Supplements & Wellness"],
    ["Electrolyte Hydration Powder", 17.99, "Electrolyte powder sticks for hydration, fitness, and travel wellness bundles.", "Supplements & Wellness"],
    ["Melatonin 5 mg Gummies", 12.99, "Melatonin gummy supplement format for sleep-support wellness categories.", "Supplements & Wellness"],
    ["Creatine Monohydrate Powder", 24.99, "Creatine powder format for fitness stores and sports nutrition resellers.", "Supplements & Wellness"],
    ["Whey Protein Powder Vanilla", 39.99, "High-demand whey protein powder format for sports nutrition and wellness stores.", "Supplements & Wellness"],
    ["Plant Protein Powder Chocolate", 36.99, "Plant-based protein powder format for vegan and wellness shoppers.", "Supplements & Wellness"],
    ["Ashwagandha Capsules", 18.99, "Adaptogen capsule format for stress-support wellness categories.", "Supplements & Wellness"],
    ["Turmeric Curcumin Capsules", 16.99, "Turmeric curcumin capsule format for everyday wellness stores.", "Supplements & Wellness"],
    ["Apple Cider Vinegar Gummies", 14.99, "Popular ACV gummy supplement format for wellness and weight-management shoppers.", "Supplements & Wellness"],
    ["CoQ10 100 mg Softgels", 21.99, "CoQ10 softgel format for premium supplement categories.", "Supplements & Wellness"],
    ["First Aid Kit 100 Piece", 24.99, "Compact first-aid kit for home, car, office, and travel resale.", "Medical & First Aid"],
    ["Adhesive Bandage Variety Pack", 7.99, "Assorted bandage pack for household and travel first-aid categories.", "Medical & First Aid"],
    ["Hydrocolloid Blister Bandages", 8.99, "Blister bandage pack for shoes, travel, sports, and foot-care shoppers.", "Medical & First Aid"],
    ["Antiseptic Wipes Pack", 6.99, "Single-use antiseptic wipe pack for first-aid kits and personal care bundles.", "Medical & First Aid"],
    ["Digital Oral Thermometer", 12.99, "Digital thermometer product type for home health and family-care stores.", "Medical & First Aid"],
    ["Infrared Forehead Thermometer", 29.99, "Contactless thermometer format for family health and home-care shoppers.", "Medical & First Aid"],
    ["Blood Pressure Monitor", 44.99, "Home blood pressure monitor product type for wellness and home health categories.", "Medical & First Aid"],
    ["Pulse Oximeter Fingertip Monitor", 19.99, "Fingertip pulse oximeter format for home health monitoring categories.", "Medical & First Aid"],
    ["Reusable Hot Cold Gel Pack", 10.99, "Hot/cold gel pack for first-aid, sports recovery, and home care.", "Medical & First Aid"],
    ["Disposable Face Mask 50 Pack", 9.99, "Face mask multipack for travel, home, salon, and general personal care resale.", "Medical & First Aid"],
    ["Nitrile Gloves 100 Pack", 14.99, "Disposable nitrile glove box for first-aid, cleaning, beauty, and home-care stores.", "Medical & First Aid"],
    ["Hand Sanitizer Travel Pack", 8.99, "Travel-size sanitizer bundle for personal care and checkout add-ons.", "Medical & First Aid"],
    ["Medical Tape Roll Pack", 6.99, "Medical tape pack for first-aid kits and household care.", "Medical & First Aid"],
    ["Elastic Compression Bandage", 7.99, "Reusable compression bandage product type for first-aid and sports care.", "Medical & First Aid"],
    ["Reusable Ear Plugs Pack", 5.99, "Ear plug pack for sleep, travel, work, and personal care categories.", "Medical & First Aid"],
].map(([name, originalPrice, description, category], index) => ({
    name: name as string,
    originalPrice: originalPrice as number,
    price: Math.round(((originalPrice as number) * 0.4) * 100) / 100,
    description: description as string,
    category: category as string,
    image: "/images/products.png",
    source: "Verified Supplier",
    sourceProductId: `wellness-seed-${index + 1}`,
    sourceUrl: "",
    isFeatured: false,
    isPromoted: false,
    sortOrder: 1000 + index,
    catalogVersion: CATALOG_VERSION,
}));

export const products = [
    ...starterProducts,
    ...wellnessCatalog,
];

// Quick lookup: product name to local image path
export const LOCAL_PRODUCT_IMAGES: Record<string, string> = Object.fromEntries(
    products.map(p => [p.name, p.image])
);

